services:
    app.form_extension.form:
        class: AppBundle\Form\Extension\FormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    app.form_extension.vich_file:
        class: AppBundle\Form\Extension\VichFileTypeExtension
        arguments:
            - "@app.attachment.link_provider"
        tags:
            - { name: form.type_extension, extended_type: Vich\UploaderBundle\Form\Type\VichFileType }
