imports:
    - { resource: filters/filters.yml }
    - { resource: simple/simple.yml }

services:
    app.form_type.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type }

    app.form_type.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - { name: form.type }

    app.form_type.application:
        class: AppBundle\Form\Type\ApplicationType
        arguments:
            - "@app.association_setter.application_attachments"
            - "@app.enum_choices.builder"
        tags:
            - { name: form.type }

    app.form_type.application_response.abstract:
        abstract: true
        arguments:
            - "@app.association_setter.application_responses"
    app.form_type.application_acceptance:
        class: AppBundle\Form\Type\ApplicationAcceptanceType
        parent: app.form_type.application_response.abstract
        tags:
            - { name: form.type }

    app.form_type.application_appeal:
        class: AppBundle\Form\Type\ApplicationAppealType
        parent: app.form_type.application_response.abstract
        tags:
            - { name: form.type }

    app.form_type.application_rejection:
        class: AppBundle\Form\Type\ApplicationRejectionType
        parent: app.form_type.application_response.abstract
        tags:
            - { name: form.type }

    app.form_type.attachment:
        class: AppBundle\Form\Type\AttachmentType
        tags:
            - { name: form.type }

    app.form_type.rejection_cause:
        class: AppBundle\Form\Type\RejectionCauseType
        tags:
            - { name: form.type }

    app.form_type.acceptance:
        class: AppBundle\Form\Type\AcceptanceType
        tags:
            - { name: form.type }

    app.form_type.appeal:
        class: AppBundle\Form\Type\AppealType
        tags:
            - { name: form.type }

    app.form_type.user:
        class: AppBundle\Form\Type\UserType
        tags:
            - { name: form.type }
