services:
    app.form_type.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type }

    app.form_type.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - { name: form.type }

    app.form_type.application:
        class: AppBundle\Form\Type\ApplicationType
        arguments:
            - "@app.util.current_user_provider"
            - "@app.association_setter.user_applications"
            - "@app.association_setter.application_attachments"
        tags:
            - { name: form.type }

    app.form_type.attachment:
        class: AppBundle\Form\Type\AttachmentType
        tags:
            - { name: form.type }
