services:
    app.form_type.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type }

    app.form_type.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - { name: form.type }

    app.form_type.application:
        class: AppBundle\Form\Type\ApplicationType
        arguments:
            - "@app.association_setter.application_attachments"
        tags:
            - { name: form.type }

    app.form_type.application_rejection:
        class: AppBundle\Form\Type\ApplicationRejectionType
        arguments:
            - "@app.association_setter.application_rejection_causes"
        tags:
            - { name: form.type }

    app.form_type.attachment:
        class: AppBundle\Form\Type\AttachmentType
        tags:
            - { name: form.type }

    app.form_type.rejection_cause:
        class: AppBundle\Form\Type\RejectionCauseType
        tags:
            - { name: form.type }

    app.form_type.user:
        class: AppBundle\Form\Type\UserType
        tags:
            - { name: form.type }
