version: '2'

services:
    database:
        container_name: granty_database
        build: docker/database
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: postgres
            POSTGRES_DB: granty

    server:
        container_name: granty_server
        build: docker/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
        volumes_from:
            - code
        volumes:
            - ./var/logs/nginx:/var/log/nginx

    php-fpm:
        container_name: granty_php_fpm
        build: docker/php
        expose:
            - "9000"
            - "9001"
        links:
            - database
        depends_on:
            - code
        volumes_from:
            - code

    code:
        container_name: granty_code
        build: docker/code
#        ports:
#            - "5000:5000"
#        environment:
#            - UNISON_WORKING_DIR=/usr/share/nginx/granty
        volumes:
            - granty-sync:/usr/share/nginx/granty:nocopy

volumes:
    granty-sync:
        external: true
