imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: pl

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 604800 # 1 week
        gc_maxlifetime: 604800  # 1 week
    fragments:       ~
    http_method_override: true
    assets: ~

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - layout/form/fields.html.twig

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@granty.agh.edu.pl
        sender_name:    Granty
    profile:
        form:
            type: AppBundle\Form\Type\ProfileType
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\Type\RegistrationType

knp_menu:
    twig:
        template: layout/menu/menu.html.twig
    templating: false
    default_renderer: twig

vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        attachment:
            upload_destination: attachment_fs
            namer: vich_uploader.namer_uniqid

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        attachment_adapter:
            local:
                directory: %kernel.root_dir%/../web/upload/attachments
    filesystems:
        attachment_fs:
            adapter: attachment_adapter