imports:
    - { resource: bundle/doctrine.yml }
    - { resource: bundle/fos_user.yml }
    - { resource: bundle/framework.yml }
    - { resource: bundle/knp_gaufrette.yml }
    - { resource: bundle/knp_menu.yml }
    - { resource: bundle/swiftmailer.yml }
    - { resource: bundle/twig.yml }
    - { resource: bundle/vich_uploader.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
