imports:
    - { resource: services/application.yml }
    - { resource: services/association_setter.yml }
    - { resource: services/attachment.yml }
    - { resource: services/filters.yml }
    - { resource: services/form.yml }
    - { resource: services/listener.yml }
    - { resource: services/menu.yml }
    - { resource: services/paginator.yml }
    - { resource: services/repository.yml }
    - { resource: services/twig.yml }
    - { resource: services/util.yml }
    - { resource: services/voter.yml }
    - { resource: services/workflow.yml }
