fos_user:
    db_driver: orm
    firewall_name: main
    use_listener: true
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@granty.agh.edu.pl
        sender_name:    Granty
    profile:
        form:
            type: AppBundle\Form\Type\ProfileType
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\Type\RegistrationType
