services:
    app.filters.form_creator:
        class: AppBundle\Service\Filters\FiltersFormCreator
        arguments:
            - "@form.factory"
            - "@request_stack"
            - "@sensio_framework_extra.converter.manager"

    app.filters.param_converter:
        class: AppBundle\Service\Filters\FiltersParamConverter
        tags:
            - { name: request.param_converter, priority: 1, converter: filters }
