services:

    app.twig.extension.attachent:
        class: AppBundle\Twig\AttachmentExtension
        arguments:
            - "@app.attachment.link_provider"
        tags:
            - { name: twig.extension }

    app.twig.extension.collection:
        class: AppBundle\Twig\CollectionExtension
        tags:
            - { name: twig.extension }

    app.twig.extension.bool:
        class: AppBundle\Twig\BoolExtension
        tags:
            - { name: twig.extension }

    app.twig.extension.filters:
        class: AppBundle\Twig\FiltersExtension
        arguments:
            - "@translator"
            - "@request_stack"
            - "@sensio_framework_extra.converter.manager"
        tags:
            - { name: twig.extension }

    app.twig.extension.application:
        class: AppBundle\Twig\ApplicationExtension
        arguments:
            - "@app.application.submitted_retriever"
        tags:
            - { name: twig.extension }

    app.twig.extension.menu:
        class: AppBundle\Twig\MenuExtension
        tags:
            - { name: twig.extension }

    app.twig.extension.traceable:
        class: AppBundle\Twig\TraceableExtension
        arguments:
            - "@translator"
            - "@app.util.current_user_provider"
        tags:
            - { name: twig.extension }
