services:
    app.workflow.application:
        class: AppBundle\Service\Workflow\Application\ApplicationWorkflow
        parent: state_machine.application
        decorates: state_machine.application
