services:
    app.voter.user.view:
        class: AppBundle\Voter\User\ViewVoter
        public: false
        tags:
            - { name: security.voter }

    app.voter.user.modify:
        class: AppBundle\Voter\User\ModifyVoter
        public: false
        tags:
            - { name: security.voter }